# Generated by Django 2.2.24 on 2022-08-26 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockuser',
            name='mobile',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
